### ISSUE TITLE
QCFC_DistDep and QCFC_DistDep_Pval have "NaN" Values

### ISSUE THREAD

**Issue by TDeramusMRI** [lindenmp/rs-fMRI#1]
Linden,

Apologies if this is a non-issue, but I'm getting values of "NaN" as output for QCFC_DistDep and QCFC_DistDep_Pval.

Not sure if its what it returns when there isn't anything of substance or the way my data is organized so I was wondering if you wouldn't mind taking a look when and if you have a minute.

Script is enclosed with the appropriate .mat files so it should run with minimal to no edits.

[Troubleshoot_Nan_Script.zip](https://github.com/lindenmp/rs-fMRI/files/1174791/Troubleshoot_Nan_Script.zip)

**Comment by lindenmp** [comment]
Hi,

This is happening because you're inputting your ROI distances as a matrix and the function expects to receive them as a vector.
Call RunQCFC like this:

`[QCFCVec,NaNFilter,QCFC_PropSig,QCFC_PropSigUnc,QCFC_AbsMed,QCFC_DistDep,QCFC_DistDep_Pval] = RunQCFC(mRMSD,ConnMatrices,LP_FlatMat(ROIdistances));
`

Note the `LP_FlatMat`

Hope this helps :)

**Comment by TDeramusMRI** [comment]
It did. Thank you. Its outputting QCFC_DistDep=0.0165 and QCFC_DistDep_Pval=0.2146 now with the corrected line.

That said, is the output telling me that of all the pairwise combinations entered, that there is not a statistically significant effect of distance dependence?

**Comment by lindenmp** [comment]
Yes, that is what it is telling you (assuming every thing lines up correctly across the variables. i.e., subjects and ROIs etc.) 

Note that the QCFC_DistDep_Pval is uncorrected so if you're running multiple pipelines and are concerned about significance of the distance dependence then you'll need to correct for multiple comparisons.
